### ISSUE TITLE
version 2.2 released

### ISSUE THREAD

**Issue by ousia** [fedora-haskell/pandoc#11]
@juhp,

version 2.2 has been released (https://github.com/jgm/pandoc/releases/latest).

It would be great if you could update it in `copr`.

BTW, there seems to be newer dependencies (at least, `pandoc-citeproc` and `pandoc-types`).

Many thanks for your help.

**Comment by juhp** [comment]
I build it some time ago, thanks

**Comment by ousia** [comment]
In the meantime, latest version ((https://github.com/jgm/pandoc/releases/latest) is 2.2.2.1.
