### ISSUE TITLE
version 2.3.1 released

### ISSUE THREAD

**Issue by ousia** [fedora-haskell/pandoc#12]
@juhp,

could you provide [version 2.3.1](https://github.com/jgm/pandoc/releases/latest) in your `copr` repository?

Many thanks for your help.

**Comment by ousia** [comment]
[pandoc 2.4](https://github.com/jgm/pandoc/releases/latest) has been released.

**Comment by juhp** [comment]
I actually prepared 2.3.1, but then forgot to build it... ugh

**Comment by juhp** [comment]
I am building both for good measure
