### ISSUE TITLE
version 2.5 released

### ISSUE THREAD

**Issue by ousia** [fedora-haskell/pandoc#13]
Version 2.5 has been released https://github.com/jgm/pandoc/releases/tag/2.5.

Description from John MacFarlane:

> This version fixes a regression in the parsing of citations, quotes, and underline emphasis after
symbols (#5099, #5053).  I recommend that everyone upgrade.
> 
> There is one API change, which necessitates the major  version number bump: A parameter for Extensions has been added to uniqueIdent and inlineListToIdentifier (#5057).
> 
> The rest of the changes are bug fixes and minor improvements, which are documented in the changelog: http://pandoc.org/releases.html#pandoc-2.5-27-november-2018

**Comment by juhp** [comment]
https://copr.fedorainfracloud.org/coprs/petersen/pandoc/monitor/detailed

**Comment by ousia** [comment]
@juhp, sorry for the delayed reply: many thanks for the update.
