### ISSUE TITLE
pandoc-types required to run filters

### ISSUE THREAD

**Issue by ousia** [fedora-haskell/pandoc#2]
According to [this](https://groups.google.com/forum/#!topic/pandoc-discuss/-1ocYUe3a6s), pandoc-types is required to run filters.

@juhp, would it be possible to package it when packaging bugfix release 1.16.0.1?

Many thanks for your help.

**Comment by juhp** [comment]
Thanks for the report.

Generally installation of libraries is tricky when building with `cabal sandbox`.
But in this case pandoc-types can be built normally separately due to light deps
(well it still builds with Fedora Haskell packages).

For now I added ghc-pandoc-types to my pandoc copr for F22+.
Though since it conflicts with the Fedora package I am inclined to move it to a separate repo.
Anyway please let me know if this helps?

**Comment by ousia** [comment]
I’m afraid it doesn’t work.

I get the following error messages when running `ghc --make nocommentsatall.hs  -v`:

```
Glasgow Haskell Compiler, Version 7.8.4, stage 2 booted by GHC version 7.8.4
Using binary package database: /usr/lib/ghc-7.8.4/package.conf.d/package.cache
wired-in package ghc-prim mapped to ghc-prim-0.3.1.0-f0b77db25e6a07f3e2798ad2aa2db4f0
wired-in package integer-gmp mapped to integer-gmp-0.5.1.0-3c6ee2f20a97b2ba60906fa87b8f151c
wired-in package base mapped to base-4.7.0.2-6d16fd65767daf67b7606bd63b471328
wired-in package rts mapped to builtin_rts
wired-in package template-haskell not found.
wired-in package dph-seq not found.
wired-in package dph-par not found.
Hsc static flags: 
wired-in package ghc-prim mapped to ghc-prim-0.3.1.0-f0b77db25e6a07f3e2798ad2aa2db4f0
wired-in package integer-gmp mapped to integer-gmp-0.5.1.0-3c6ee2f20a97b2ba60906fa87b8f151c
wired-in package base mapped to base-4.7.0.2-6d16fd65767daf67b7606bd63b471328
wired-in package rts mapped to builtin_rts
wired-in package template-haskell not found.
wired-in package dph-seq not found.
wired-in package dph-par not found.
*** Chasing dependencies:
Chasing modules from: *nocommentsatall.hs

nocommentsatall.hs:5:8:
    Could not find module ‘Text.Pandoc.JSON’
    Locations searched:
      Text/Pandoc/JSON.hs
      Text/Pandoc/JSON.lhs

nocommentsatall.hs:6:8:
    Could not find module ‘Text.Pandoc.Walk’
    Locations searched:
      Text/Pandoc/Walk.hs
      Text/Pandoc/Walk.lhs
*** Deleting temp files:
Deleting: 
*** Deleting temp dirs:
Deleting: 
```

**Comment by ousia** [comment]
Of course, many thanks for the new package (I forgot).

I will ask about this at the mailing list.

**Comment by ousia** [comment]
@juhp, it was totally my fault. I had to install `ghc-pandoc-types-devel` and everything works fine now.

Closing the issue myself.

**Comment by juhp** [comment]
Cool :+1:

**Comment by juhp** [comment]
Moving it to https://copr.fedorainfracloud.org/coprs/petersen/ghc-pandoc-types/
