### ISSUE TITLE
version 1.18

### ISSUE THREAD

**Issue by ousia** [fedora-haskell/pandoc#6]
@juhp, would it be possible to release latest pandoc version also for Fedora 23?

Many thanks for your help.

**Comment by juhp** [comment]
Thanks of the headsup.  Done.

https://copr.fedorainfracloud.org/coprs/petersen/pandoc/build/471424/

**Comment by ousia** [comment]
@juhp, many thanks for the build.

I’m experiencing issue #2 again. Filters require that `ghc-pandoc-types` is updated to latest version.

Many thanks for your awesome work.
