### ISSUE TITLE
pandoc filters require latest ghc-pandoc-types-devel

### ISSUE THREAD

**Issue by ousia** [fedora-haskell/pandoc#7]
@juhp, sorry for bothering you with this issue.

I’m afraid that `pandoc-1.18` requires the latest version of `ghc-pandoc-types-devel` (1.17.0.4):

```
Compiled with pandoc-types 1.17.0.4,
```

I’m afraid this is the only way to compile filters and to deploy them.

Many thanks for your help.

**Comment by juhp** [comment]
I see thanks for reporting this: I wonder if this should be fixed upstream then?
Sorry for the slow reply I have been traveling.

So you have (re)built it yourself?
Have you discussed it upstream or could you could report it [there](https://github.com/jgm/pandoc/issues) too?
But if they are not able to roll out an update I can patch the copr package.
I guess the "problem" might be that not that many people use pandoc filters...

**Comment by ousia** [comment]
Many thanks for your help, @juhp.

BTW, your replies are always fast, so I thought the delay should have a good reason :smile:.

Programming is all Greek to me. This especially applies to Haskell. Sorry, but for the ignorant, Python or Lua resemble some sort of English syntax. Functional programming is for smarter people.

I don’t think this needs any fixing upstream. `pandoc-types` is an independent package from `pandoc`.

Filters require `pandoc-types` (https://github.com/jgm/pandoc-types [in Fedora Haskell `ghc-pandoc-types-devel`]) to be compiled.

`pandoc-1.18` has been compiled with `pandoc-types-1.17.0.4`. The same version is required to compile filters. Versions should match.

Sorry, but the way I see it is that they are being offered as different packages. And filter compilation requires the matching `ghc-pandoc-types-devel` package.

I may be missing something, please correct my wrong assumptions.

**Comment by juhp** [comment]
Ah I see sorry - I thought you were asking me to recompile pandoc with newer pandoc-types...
but it so already so as you point out.  Probably it was you who asked me to add ghc-pandoc-types to the copr repo, but I had kind of forgotten about it. Anyway I understand now: pandoc-1.18 needs pandoc-types-1.17 yes, so I will update it.

Thanks for reporting.

**Comment by ousia** [comment]
Many thanks for updating `pandoc-types`.

And yes, I was the one who asked for including it to compile the filters (#2).

**Comment by ousia** [comment]
After waiting for the release (I thought that copr was delaying it for some reason unknown to me :smile:), I have just discovered that it was available from Monday 14th, but only for Fedora 25 and Rawhide.

Would it be possible to release it for both Fedora 23 and 24?

**Comment by juhp** [comment]
(I am moving it to https://copr.fedorainfracloud.org/coprs/petersen/ghc-pandoc-types/)
