### ISSUE TITLE
version 2.0

### ISSUE THREAD

**Issue by ousia** [fedora-haskell/pandoc#8]
@juhp, version 2.0 has been released.

Could you package it for `copr`?

Many thanks for your help.

**Comment by juhp** [comment]
I want to, but currently I can't build Haskell packages in Copr due to https://bugzilla.redhat.com/show_bug.cgi?id=1467299

**Comment by juhp** [comment]
I have updated the git repo here to pandoc-2.0.0.1.

You can also try to build it locally or `cabal install pandoc`.

**Comment by ousia** [comment]
Many thanks for your help, @juhp.

I think I will wait until the issue with `mock` is fixed.

I’m afraid that either a local build or `cabal install pandoc` are too complex for me.

**Comment by ousia** [comment]
@juhp, I have just installed version 2.0.0.1 for Fedora 25. Many thanks for your work.

Just in case it helps, [a newer version has been released](https://github.com/jgm/pandoc/releases/latest).

Closing the issue myself.
