### ISSUE TITLE
version 2.1.1

### ISSUE THREAD

**Issue by ousia** [fedora-haskell/pandoc#9]
@juhp,

`pandoc-2.1.1` has been released just now.

Among many other things, an issue with wrong stripped comments (using the option `--strip-comments`) has been fixed. It comes with newer `pandoc-citeproc` and `pandoc-types` releases.

Could you package it for the copr repo?

Many thanks for your help.

**Comment by ousia** [comment]
@juhp,

I have already installed Fedora 26 (and this week I may install Fedora 27).

Would it be possible to have `pandoc-2.1.1` in the the copr repository?

Many thanks for your help.

**Comment by juhp** [comment]
It failed to build for me locally with ghc-8.0.2

```
src/Text/Pandoc/Writers/HTML.hs:918:19: error:
    • The constructor ‘Empty’ should have no arguments, but has been given 1
    • In the pattern: Empty _
      In an equation for ‘nonempty’: nonempty (Empty _) = False
      In an equation for ‘blockListToHtml’:
          blockListToHtml opts lst
            = (mconcat . intersperse (nl opts) . filter nonempty)
              <$> mapM (blockToHtml opts) lst
            where
                nonempty (Empty _) = False
                nonempty _ = True
```

**Comment by ousia** [comment]
@juhp, just reported in jgm/pandoc#4380.

**Comment by juhp** [comment]
Okay I built 2.1.1 in Copr for Fedora and EL7.

**Comment by ousia** [comment]
Many thanks for the builds, @juhp.

I have just downloaded (manually) and installed them.

Just a comment, `ghc-pandoc-types` has a newer version ([1.17.3.1](https://github.com/jgm/pandoc-types/releases)).

**Comment by juhp** [comment]
Okay here's https://copr.fedorainfracloud.org/coprs/petersen/pandoc/build/719143/

(self note fedora-haskell/pandoc#2)

**Comment by ousia** [comment]
Many thanks for the new builds.

I have just installed them.

**Comment by juhp** [comment]
I think I will move ghc-pandoc-types to https://copr.fedorainfracloud.org/coprs/petersen/ghc-pandoc-types/ since I don't like dnf complaining about it conflicting with Fedora's ghc-pandoc-types, though maybe only few people actually have it installed..?

**Comment by ousia** [comment]
Many thanks for the new repo, @juhp.
